model:
    arch: psp101
    backbone: resnet50
    syncBN: True
    
data:
    train_split: train
    val_split: val
    test_split: test
    img_rows: 432
    img_cols: 623

training:
    n_workers: 8
    train_iters: 40000
    batch_size: 3
    val_interval: 350
    print_interval: 100
    loss:
        name: CrossEntropyLoss
        aux_weight: 0.4
        ignore_index: 255
    optimizer:
        name: adaoptimizer
        momentum: 0.9
        wd: 1.0e-4
        lr0: 1.0e-2
        max_iter: 40000
        power: 0.9
        warmup_steps: 400
        warmup_start_lr: 1.0e-5
    train_augmentations:
        # rotate: 5
        colorjtr: [0.5,0.5,0.5]
        scale: [432,623]
        hflip: 0.5
        rscale: [0.75, 1.0, 1.25, 1.5, 1.75, 2.0]
        rcrop: [432,623]
        colornorm: [[0.485, 0.456, 0.406], [0.229, 0.224, 0.225]]
    resume: /home/crx_pinkpanda1/RGB-V/TDNet/pretrained/psp50.pkl
    visdom: False

validating:
    resume: /data/lj/lightfiled/dan_picseg/selfattention/v3_2/psp101_best_model_7700.pkl
    n_workers: 2
    batch_size: 1
    scales: [1.5,1.25,1,0.75]
    flip: true
    mult_scale: true
    base_size_h: 423
    base_size_w: 623
    val_augmentations:
        scale: [423,623]
        colornorm: [[0.485, 0.456, 0.406], [0.229, 0.224, 0.225]]
